name: versionMinor

# This workflow runs whenever a pull request is opened from main into stage
# It updates the minor version number, the dynamic badges, and release changelog

on:
  pull_request:
    types:
      - opened
    branches:
      - stage

concurrency:
  group: octogration

jobs:
  prod_release:
    if: github.event.pull_request.head.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          token: ${{ secrets.OCTO_PAT }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: lock pull request
        uses: sudo-bot/action-pull-request-lock@v1.1.0
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            number: ${{ github.event.pull_request.number }}

      - name: Ensure correct npm version
        run: npm i --location=global npm@8.3.1 --registry=https://registry.npmjs.org

      - name: Configure github
        run: |
          git fetch
          git config user.email "octogration@ready.net"
          git config user.name "Octogration"
          git checkout main

      - name: Upgrade version of project
        run: npm version minor -m "v%s"

      - name: Send version upgrade commit to github
        run: |
          git push "https://octogration:${{ secrets.OCTO_PAT }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags
          git push "https://octogration:${{ secrets.OCTO_PAT }}@github.com/$GITHUB_REPOSITORY.git" --tags

      - run: npm ci

      - name: Update dynamic badges
        run: npx octogration badges version,lastProd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create changelog
        run: npx octogration changelog ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send dynamic badges commit to github
        run: |
          git pull
          git add .
          git commit -nm "chore: update dynamic badges"
          git push "https://octogration:${{ secrets.OCTO_PAT }}@github.com/$GITHUB_REPOSITORY.git"

      - uses: OSDKDev/unlock-issues@v1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
